version: '3'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 200k
    max-file: 2

services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "${HOST_SMTP_PORT:-1025}:1025"
  db:
    logging: *default-logging
    image: postgres:14-alpine
    ports:
      - "${HOST_PG_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  ui:
    logging: *default-logging
    build:
      context: .
      dockerfile: ./packages/result-app-ember/Dockerfile
  api:
    logging: *default-logging
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./packages/result-app-nest/Dockerfile
    environment:
      SERVER_PORT: 3000
  web:
    logging: *default-logging
    image: nginx
    depends_on:
      - ui
      - api
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dev.crt:/etc/certs/dev.crt
      - ./dev.key:/etc/certs/dev.key
      - ./local-dev/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  npm_cache: