version: '3'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 200k
    max-file: 2

services:
  db:
    logging: *default-logging
    image: postgres:14-alpine
    ports:
      - "${HOST_PG_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  ui:
    logging: *default-logging
    build:
      context: ./result-app-ember
  api:
    logging: *default-logging
    depends_on:
      - db
    build:
      context: ./result-app-nest
  web:
    logging: *default-logging
    image: nginx
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dev.crt:/etc/certs/dev.crt
      - ./dev.key:/etc/certs/dev.key
      - ./local-dev/nginx.conf:/etc/nginx/conf.d/default.conf